### ISSUE TITLE
Textfield does not have a correct size

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_components#114]
The workaround can be found here https://github.com/flutter/flutter/issues/108813#issuecomment-1227167330

**Comment by dhanvi1911** [comment]
hey, Can you assign it to me?

**Comment by dhanvi1911** [comment]
Could you explain the error more precisely?

**Comment by jonas-martinez** [comment]
Hi @dhanvi1911,

The problem here is exactly the same as the mentioned issue https://github.com/flutter/flutter/issues/108813#issuecomment-1227167330. There is a problem with the textfield where the content is bigger than the outline of the textfield. This causes the text to not be centered inside of the textfield.

There is no real solution except a workaround with the `visualDensity` property that must be set to `VisualDensity.standard` inside of the ThemeData. I don't know if this is possible with our current implementation of LenraThemeData (lenra_theme_data.dart) 

If you still wish to work on this issue, the instruction will be almost the same as my comment on another issue assigned to you https://github.com/lenra-io/lenra_components/issues/105#issuecomment-1247269354

**Comment by jonas-martinez** [comment]
It seems that the fix using `visualDensity: VisualDensity.standard` does not break anything. Textfields feels much bigger but the text is properly centered and sized inside of it. 
Maybe I missed something that was broken by this fix, so be extra careful when doing the review.

**Comment by jonas-martinez** [comment]
This has been fixed by https://github.com/lenra-io/client-store/pull/27 and https://github.com/lenra-io/client-backoffice/pull/47
